#!/bin/bash

update_repo() {
    git stash
    git pull --force
    git submodule update --init --recursive
}

if [[ "$1" == "-c" ]]; then
    update_repo
    npm start
elif [[ "$1" == "-d" ]]; then
    update_repo
    npm run rssify
else
    npm run rssify
fi
